export const GET_ALL_APPOINTMENTS = "GET_ALL_APPOINTMENTS"
export const GET_ALL_APPOINTMENTS_SUCCESS = "GET_ALL_APPOINTMENTS_SUCCESS"
export const GET_ALL_APPOINTMENTS_FAIL = "GET_ALL_APPOINTMENTS_FAIL"

export const POST_APPOINTMENT = "POST_APPOINTMENT"
export const POST_APPOINTMENT_SUCCESS = "POST_APPOINTMENT_SUCCESS"
export const POST_APPOINTMENT_FAIL = "POST_APPOINTMENT_FAIL"