export const GET_ALL_STAFFMEMBERS = "GET_ALL_STAFFMEMBERS"
export const GET_ALL_STAFFMEMBERS_SUCCESS = "GET_ALL_STAFFMEMBERS_SUCCESS"
export const GET_ALL_STAFFMEMBERS_FAIL = "GET_ALL_STAFFMEMBERS_FAIL"